#!/usr/bin/env bash
set -e

USER=team254
HOST=ec2.team254.com
APP=chezy-champs-website

echo "Deploying $APP from Git master branch..."
echo
ssh $USER@$HOST "cd /opt/sites/$APP && git checkout -f && git pull"
echo
echo "Deployed $APP."
